/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AppPantryRouteImport } from './routes/_app/pantry'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppWeekRouteImport } from './routes/_app/week'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AppListIndexRouteImport } from './routes/_app/list/index'
import { Route as AppRecipesIndexRouteImport } from './routes/_app/recipes/index'
import { Route as AppRecipesNewRouteImport } from './routes/_app/recipes/new'
import { Route as AppRecipesRecipeIdIndexRouteImport } from './routes/_app/recipes/$recipeId/index'
import { Route as AppRecipesRecipeIdEditRouteImport } from './routes/_app/recipes/$recipeId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPantryRoute = AppPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWeekRoute = AppWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AppRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppListIndexRoute = AppListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIndexRoute = AppRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesNewRoute = AppRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRecipeIdIndexRoute = AppRecipesRecipeIdIndexRouteImport.update({
  id: '/recipes/$recipeId/',
  path: '/recipes/$recipeId/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRecipeIdEditRoute = AppRecipesRecipeIdEditRouteImport.update({
  id: '/recipes/$recipeId/edit',
  path: '/recipes/$recipeId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/pantry': typeof AppPantryRoute
  '/settings': typeof AppSettingsRoute
  '/week': typeof AppWeekRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/list/': typeof AppListIndexRoute
  '/recipes/': typeof AppRecipesIndexRoute
  '/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/recipes/$recipeId/': typeof AppRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/pantry': typeof AppPantryRoute
  '/settings': typeof AppSettingsRoute
  '/week': typeof AppWeekRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/list': typeof AppListIndexRoute
  '/recipes': typeof AppRecipesIndexRoute
  '/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/recipes/$recipeId': typeof AppRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/join': typeof JoinRoute
  '/_app/pantry': typeof AppPantryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/week': typeof AppWeekRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_app/recipes/new': typeof AppRecipesNewRoute
  '/_app/list/': typeof AppListIndexRoute
  '/_app/recipes/': typeof AppRecipesIndexRoute
  '/_app/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/_app/recipes/$recipeId/': typeof AppRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/pantry'
    | '/settings'
    | '/week'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/recipes/new'
    | '/list/'
    | '/recipes/'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/pantry'
    | '/settings'
    | '/week'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/recipes/new'
    | '/list'
    | '/recipes'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/join'
    | '/_app/pantry'
    | '/_app/settings'
    | '/_app/week'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_app/recipes/new'
    | '/_app/list/'
    | '/_app/recipes/'
    | '/_app/recipes/$recipeId/edit'
    | '/_app/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  JoinRoute: typeof JoinRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pantry': {
      id: '/_app/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AppPantryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/week': {
      id: '/_app/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AppWeekRouteImport
      parentRoute: typeof AppRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/list/': {
      id: '/_app/list/'
      path: '/list'
      fullPath: '/list/'
      preLoaderRoute: typeof AppListIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/': {
      id: '/_app/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AppRecipesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/new': {
      id: '/_app/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AppRecipesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$recipeId/': {
      id: '/_app/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof AppRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$recipeId/edit': {
      id: '/_app/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof AppRecipesRecipeIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppPantryRoute: typeof AppPantryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWeekRoute: typeof AppWeekRoute
  AppRecipesNewRoute: typeof AppRecipesNewRoute
  AppListIndexRoute: typeof AppListIndexRoute
  AppRecipesIndexRoute: typeof AppRecipesIndexRoute
  AppRecipesRecipeIdEditRoute: typeof AppRecipesRecipeIdEditRoute
  AppRecipesRecipeIdIndexRoute: typeof AppRecipesRecipeIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPantryRoute: AppPantryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWeekRoute: AppWeekRoute,
  AppRecipesNewRoute: AppRecipesNewRoute,
  AppListIndexRoute: AppListIndexRoute,
  AppRecipesIndexRoute: AppRecipesIndexRoute,
  AppRecipesRecipeIdEditRoute: AppRecipesRecipeIdEditRoute,
  AppRecipesRecipeIdIndexRoute: AppRecipesRecipeIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  JoinRoute: JoinRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
