/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as JoinRouteImport } from './routes/join'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AppCloseoutRouteImport } from './routes/_app/closeout'
import { Route as AppLeftoversRouteImport } from './routes/_app/leftovers'
import { Route as AppPantryRouteImport } from './routes/_app/pantry'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AppListIndexRouteImport } from './routes/_app/list/index'
import { Route as AppListReconcileRouteImport } from './routes/_app/list/reconcile'
import { Route as AppRecipesIndexRouteImport } from './routes/_app/recipes/index'
import { Route as AppRecipesNewRouteImport } from './routes/_app/recipes/new'
import { Route as AppWeekIndexRouteImport } from './routes/_app/week/index'
import { Route as AppWeekPlanRouteImport } from './routes/_app/week/plan'
import { Route as AppRecipesRecipeIdIndexRouteImport } from './routes/_app/recipes/$recipeId/index'
import { Route as AppRecipesRecipeIdEditRouteImport } from './routes/_app/recipes/$recipeId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCloseoutRoute = AppCloseoutRouteImport.update({
  id: '/closeout',
  path: '/closeout',
  getParentRoute: () => AppRoute,
} as any)
const AppLeftoversRoute = AppLeftoversRouteImport.update({
  id: '/leftovers',
  path: '/leftovers',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryRoute = AppPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppListIndexRoute = AppListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => AppRoute,
} as any)
const AppListReconcileRoute = AppListReconcileRouteImport.update({
  id: '/list/reconcile',
  path: '/list/reconcile',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIndexRoute = AppRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesNewRoute = AppRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWeekIndexRoute = AppWeekIndexRouteImport.update({
  id: '/week/',
  path: '/week/',
  getParentRoute: () => AppRoute,
} as any)
const AppWeekPlanRoute = AppWeekPlanRouteImport.update({
  id: '/week/plan',
  path: '/week/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRecipeIdIndexRoute = AppRecipesRecipeIdIndexRouteImport.update({
  id: '/recipes/$recipeId/',
  path: '/recipes/$recipeId/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRecipeIdEditRoute = AppRecipesRecipeIdEditRouteImport.update({
  id: '/recipes/$recipeId/edit',
  path: '/recipes/$recipeId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/mcp': typeof McpRoute
  '/closeout': typeof AppCloseoutRoute
  '/leftovers': typeof AppLeftoversRoute
  '/pantry': typeof AppPantryRoute
  '/settings': typeof AppSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/list/reconcile': typeof AppListReconcileRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/week/plan': typeof AppWeekPlanRoute
  '/list/': typeof AppListIndexRoute
  '/recipes/': typeof AppRecipesIndexRoute
  '/week/': typeof AppWeekIndexRoute
  '/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/recipes/$recipeId/': typeof AppRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/mcp': typeof McpRoute
  '/closeout': typeof AppCloseoutRoute
  '/leftovers': typeof AppLeftoversRoute
  '/pantry': typeof AppPantryRoute
  '/settings': typeof AppSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/list/reconcile': typeof AppListReconcileRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/week/plan': typeof AppWeekPlanRoute
  '/list': typeof AppListIndexRoute
  '/recipes': typeof AppRecipesIndexRoute
  '/week': typeof AppWeekIndexRoute
  '/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/recipes/$recipeId': typeof AppRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/mcp': typeof McpRoute
  '/_app/closeout': typeof AppCloseoutRoute
  '/_app/leftovers': typeof AppLeftoversRoute
  '/_app/pantry': typeof AppPantryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_app/list/reconcile': typeof AppListReconcileRoute
  '/_app/recipes/new': typeof AppRecipesNewRoute
  '/_app/week/plan': typeof AppWeekPlanRoute
  '/_app/list/': typeof AppListIndexRoute
  '/_app/recipes/': typeof AppRecipesIndexRoute
  '/_app/week/': typeof AppWeekIndexRoute
  '/_app/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/_app/recipes/$recipeId/': typeof AppRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/join'
    | '/mcp'
    | '/closeout'
    | '/leftovers'
    | '/pantry'
    | '/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/list/reconcile'
    | '/recipes/new'
    | '/week/plan'
    | '/list/'
    | '/recipes/'
    | '/week/'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/join'
    | '/mcp'
    | '/closeout'
    | '/leftovers'
    | '/pantry'
    | '/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/list/reconcile'
    | '/recipes/new'
    | '/week/plan'
    | '/list'
    | '/recipes'
    | '/week'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/gallery'
    | '/join'
    | '/mcp'
    | '/_app/closeout'
    | '/_app/leftovers'
    | '/_app/pantry'
    | '/_app/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_app/list/reconcile'
    | '/_app/recipes/new'
    | '/_app/week/plan'
    | '/_app/list/'
    | '/_app/recipes/'
    | '/_app/week/'
    | '/_app/recipes/$recipeId/edit'
    | '/_app/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  JoinRoute: typeof JoinRoute
  McpRoute: typeof McpRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/closeout': {
      id: '/_app/closeout'
      path: '/closeout'
      fullPath: '/closeout'
      preLoaderRoute: typeof AppCloseoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leftovers': {
      id: '/_app/leftovers'
      path: '/leftovers'
      fullPath: '/leftovers'
      preLoaderRoute: typeof AppLeftoversRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pantry': {
      id: '/_app/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AppPantryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/list/': {
      id: '/_app/list/'
      path: '/list'
      fullPath: '/list/'
      preLoaderRoute: typeof AppListIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/list/reconcile': {
      id: '/_app/list/reconcile'
      path: '/list/reconcile'
      fullPath: '/list/reconcile'
      preLoaderRoute: typeof AppListReconcileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/': {
      id: '/_app/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AppRecipesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/new': {
      id: '/_app/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AppRecipesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/week/': {
      id: '/_app/week/'
      path: '/week'
      fullPath: '/week/'
      preLoaderRoute: typeof AppWeekIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/week/plan': {
      id: '/_app/week/plan'
      path: '/week/plan'
      fullPath: '/week/plan'
      preLoaderRoute: typeof AppWeekPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$recipeId/': {
      id: '/_app/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof AppRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$recipeId/edit': {
      id: '/_app/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof AppRecipesRecipeIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCloseoutRoute: typeof AppCloseoutRoute
  AppLeftoversRoute: typeof AppLeftoversRoute
  AppPantryRoute: typeof AppPantryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppListReconcileRoute: typeof AppListReconcileRoute
  AppRecipesNewRoute: typeof AppRecipesNewRoute
  AppWeekPlanRoute: typeof AppWeekPlanRoute
  AppListIndexRoute: typeof AppListIndexRoute
  AppRecipesIndexRoute: typeof AppRecipesIndexRoute
  AppWeekIndexRoute: typeof AppWeekIndexRoute
  AppRecipesRecipeIdEditRoute: typeof AppRecipesRecipeIdEditRoute
  AppRecipesRecipeIdIndexRoute: typeof AppRecipesRecipeIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCloseoutRoute: AppCloseoutRoute,
  AppLeftoversRoute: AppLeftoversRoute,
  AppPantryRoute: AppPantryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppListReconcileRoute: AppListReconcileRoute,
  AppRecipesNewRoute: AppRecipesNewRoute,
  AppWeekPlanRoute: AppWeekPlanRoute,
  AppListIndexRoute: AppListIndexRoute,
  AppRecipesIndexRoute: AppRecipesIndexRoute,
  AppWeekIndexRoute: AppWeekIndexRoute,
  AppRecipesRecipeIdEditRoute: AppRecipesRecipeIdEditRoute,
  AppRecipesRecipeIdIndexRoute: AppRecipesRecipeIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  GalleryRoute: GalleryRoute,
  JoinRoute: JoinRoute,
  McpRoute: McpRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
